### ISSUE TITLE
Swift 2.0, Please

### ISSUE THREAD

**Issue by rankun203** [Kitware/arctic-viewer-ios#1]
I'm learning the basic stuff of using swift to make a http server that serves files, and found your amazing repo, just can't get it run on my phone.

If it's in swift 2.0, I would be very grateful, thank you :)

**Comment by jourdain** [comment]
Hum, I'll let @TristanWright get back to you on that but I'm pretty sure we did not used Swift 2.0 as it was not available when we wrote the code.

Can you elaborate your issue on your phone? 

BTW the application is also available on the AppStore for free if you want.

**Comment by rankun203** [comment]
Yea, I’m very glad that it’s in the App Store, and I’ve downloaded it ;)

And my problem is, I tried to open the project in my Xcode 7, and Xcode doesn’t like to compile the source code, and threws me tons of error, and I converted the source code to latest swift style, but the error just more and more, I solved some of them, but still left tons of issues unresolved.

For play the App, I’ve installed the App on my Phone, so I’m glad.
Just wondering if the project is in Swift 2.0, that would be much much better :)

—
Regards,Kun

**Comment by jourdain** [comment]
Did you follow the steps described in the Readme? 

Anyhow, we are planning to upgrade to the latest version of Xcode and Swift, so that should not be a problem down the road. But I can't give you a timeline for now. Hopefully we can do it in the coming month.

**Comment by rankun203** [comment]
Thank you very much.

—
Regards,Kun

**Comment by TristanWright** [comment]
Yes to what @jourdain said. Swift 2.0/XCode 7 was still in beta when we were developing this. If you're interested in just the server component, we're using the last version of [Swifter](https://github.com/glock45/swifter) that worked with Swift 1.2. It's compatible with Swift 2.0 right now and has improved a bit since we started using it.
